@startuml

skin rose

' left to right direction
set namespaceSeparator .
skinparam MaxMessageSize 50

package voice_ui {
   component VoiceUI

   package speech_detection {
      component speech_detector.SpeechDetector
      package vad_microphone {
         component MicrophoneVADStream
         component HotwordDetector
      }
      component speaker_profile_manager.SpeakerProfileManager
   }

   package speech_recognition {
      component speech_to_text_transcriber_factory.SpeechToTextTranscriberFactory
      component speech_to_text_transcriber.SpeechToTextTranscriber

      SpeechToTextTranscriberFactory .> SpeechToTextTranscriber

      component openai_whisper.WhisperTranscriber
      component openai_local_whisper.LocalWhisperTranscriber

      SpeechToTextTranscriber <|.. WhisperTranscriber
      SpeechToTextTranscriber <|.. LocalWhisperTranscriber
      SpeechToTextTranscriberFactory --> WhisperTranscriber
      SpeechToTextTranscriberFactory --> LocalWhisperTranscriber
   }

   package speech_synthesis {
      component text_to_speech_streamer.TextToSpeechAudioStreamer
      component text_to_speech_streamer_factory.TextToSpeechAudioStreamerFactory

      TextToSpeechAudioStreamerFactory .> TextToSpeechAudioStreamer

      component pass_through_text_to_speech_streamer.PassThroughTextToSpeechAudioStreamer
      component google_text_to_speech_streamer.GoogleTextToSpeechAudioStreamer
      component open_ai_text_to_speech_streamer.OpenAITextToSpeechAudioStreamer

      TextToSpeechAudioStreamer <|.. PassThroughTextToSpeechAudioStreamer
      PassThroughTextToSpeechAudioStreamer <|-- GoogleTextToSpeechAudioStreamer
      PassThroughTextToSpeechAudioStreamer <|-- OpenAITextToSpeechAudioStreamer

      TextToSpeechAudioStreamerFactory --> GoogleTextToSpeechAudioStreamer
      TextToSpeechAudioStreamerFactory --> OpenAITextToSpeechAudioStreamer
      TextToSpeechAudioStreamerFactory --> PassThroughTextToSpeechAudioStreamer
   }

   package audio_io {
      component audio_data.AudioData
      component microphone.MicrophoneStream
      component player.Player
   }

   package voice_activity_detection {
      component vad_i.IVoiceActivityDetector
      component vad_factory.VADFactory

      VADFactory .> IVoiceActivityDetector

      component vad_picovoice.PicoVoiceVAD
      component vad_funasr.FunASRVAD
      component vad_silero.SileroVAD

      IVoiceActivityDetector <|.. PicoVoiceVAD
      IVoiceActivityDetector <|.. FunASRVAD
      IVoiceActivityDetector <|.. SileroVAD

      VADFactory --> PicoVoiceVAD
      VADFactory --> FunASRVAD
      VADFactory --> SileroVAD
   }
}

VoiceUI --* SpeechDetector
VoiceUI --> SpeechToTextTranscriberFactory: create()
VoiceUI --o SpeechToTextTranscriber: transcribe()
VoiceUI --* TextToSpeechAudioStreamer: speak(), stop()
VoiceUI --> TextToSpeechAudioStreamerFactory: create()

PassThroughTextToSpeechAudioStreamer --o Player: play_data()
' OpenAITextToSpeechAudioStreamer --o [requests]
' GoogleTextToSpeechAudioStreamer --o [google]

SpeechDetector --* SpeakerProfileManager: load_profiles()
SpeechDetector --* MicrophoneVADStream: resume(), stop(), generator()
SpeechDetector --* [picovoice.pveagle.Eagle]: create_recognizer()

SpeakerProfileManager --o [picovoice.pveagle.EagleProfiler]: create_profiler()
SpeakerProfileManager --o [picovoice.pveagle.EagleProfile]: from_bytes()
SpeakerProfileManager --o [picovoice.pvrecorder.PvRecorder]: start(), read(), stop(), delete()

MicrophoneStream <|-- MicrophoneVADStream
MicrophoneVADStream --> VADFactory: create()
MicrophoneVADStream --* IVoiceActivityDetector: process()
MicrophoneVADStream --* [picovoice.pveagle.Eagle]: process(), delete()
MicrophoneVADStream --o [picovoice.pveagle.EagleProfiler]
MicrophoneVADStream -* HotwordDetector: process()

MicrophoneStream --* [pyaudio.PyAudio]
Player --* [pyaudio.PyAudio]

HotwordDetector --* [picovoice.pvporcupine.Porcupine]

[plugins.voice_profiler.VoiceProfileManager] --* SpeakerProfileManager: load_profile(), create_profile(), list_profiles()

note top of [plugins.voice_profiler.VoiceProfileManager]
   <b>TODO:</b> Make this plugin use the SpeakerProfileManager
end note

WhisperTranscriber --* [openai.OpenAI]

SpeechDetector ..> AudioData
WhisperTranscriber ..> AudioData
LocalWhisperTranscriber ..> AudioData
SpeechToTextTranscriber ..> AudioData
PassThroughTextToSpeechAudioStreamer ..> AudioData

' PicoVoiceVAD --* [picovoice.pvcobra.Cobra]: process(), delete()

@enduml